using System.Reflection;
using Kadense.RPG.Dice;

namespace Kadense.RPG.Games;

public partial class GamesFactory : GameBase
{
    [Game("Dead Channel")]
    public GamesFactory DeadChannel()
    {
        var attr = MethodInfo.GetCurrentMethod()!.GetCustomAttribute<GameAttribute>()!;
        return this
            .WithGame(attr.Name, attr.Description ?? "TBD Add Description")
                .WithWorldSection()
                    .WithSelection("Location")
                        .WithNewChoice("School")
                        .WithNewChoice("Remote Cabin")
                        .WithNewChoice("Warehouse Rave")
                        .WithNewChoice("Large Family Home")
                        .WithNewChoice("Hospital")
                        .WithNewChoice("Fairground")
                    .End()
                    .WithSelection("Threat")
                        .WithNewChoice("Vampires")
                        .WithNewChoice("Werewolves")
                        .WithNewChoice("Witches")
                        .WithNewChoice("Demons")
                        .WithNewChoice("Possesor Spirit")
                        .WithNewChoice("Creepy Cult")
                    .End()
                    .WithSelection("Threat Weakness (or use the traditional ones)")
                        .WithNewChoice("Sunlight")
                        .WithNewChoice("Silver")
                        .WithNewChoice("Fire")
                        .WithNewChoice("Magic")
                        .WithNewChoice("Exorcism")
                        .WithNewChoice("Salt")
                    .End()
                    .WithSelection("Plot twist")
                        .WithNewChoice("The threat is summoning a bigger threat")
                        .WithChoice("Threat is actually")
                            .WithSelection("New Threat")
                                .WithNewChoice("Vampires")
                                .WithNewChoice("Werewolves")
                                .WithNewChoice("Witches")
                                .WithNewChoice("Demons")
                                .WithNewChoice("Possesor Spirit")
                                .WithNewChoice("Creepy Cult")
                            .End()
                        .End()
                        .WithNewChoice("The government did it")
                        .WithNewChoice("This is all your fault")
                        .WithNewChoice("Random PC is behind the threat")
                        .WithNewChoice("Your shelter burns, floods, etc")
                    .End()
                .End()
                .WithCharacterSection()
                    .WithSelection("Primary")
                        .WithChoice("Strong")
                            .WithSelection("Secondary")
                                .WithNewChoice("Morbid Curiousity")
                                .WithNewChoice("Over-Protective")
                                .WithNewChoice("Something to prove")
                            .End()
                        .End()
                        .WithChoice("Weird")
                            .WithSelection("Secondary")
                                .WithNewChoice("Too Dumb to be Scared")
                                .WithNewChoice("Over-Protective")
                                .WithNewChoice("Something to prove")
                            .End()
                        .End()
                        .WithChoice("Smart")
                            .WithSelection("Secondary")
                                .WithNewChoice("Too Dumb to be Scared")
                                .WithNewChoice("Morbid Curiousity")
                                .WithNewChoice("Something to prove")
                            .End()
                        .End()
                        .WithChoice("Hot")
                            .WithSelection("Secondary")
                                .WithNewChoice("Too Dumb to be Scared")
                                .WithNewChoice("Morbid Curiousity")
                                .WithNewChoice("Over-Protective")
                            .End()
                        .End()
                    .End()
                    .WithSelection("I just want")
                        .WithNewChoice("Hot makeouts")
                        .WithNewChoice("Recreational drugs")
                        .WithNewChoice("Fun memories")
                        .WithNewChoice("To make a true friend")
                        .WithNewChoice("Respect")
                        .WithNewChoice("Everyone to love me")
                    .End()
                .End()
            .End();
    }
}

