using System.Reflection;

namespace Kadense.RPG.Games;

public partial class GamesFactory : GameBase
{
    [Game("The Rapid and The Righteous")]
    public GamesFactory TheRapidAndTheRighteous()
    {
        var attr = MethodInfo.GetCurrentMethod()!.GetCustomAttribute<GameAttribute>()!;
        return this
            .WithGame(attr.Name, attr.Description ?? "TBD Add Description")
                .WithWorldSection()
                    .WithLlmPrompt(@"""I need a narrative introduction for a game set in current times. The game takes place in {city}, where a street-racing gang run by a {villianGender} {villianPersonality} {villainType} and his right hand, a {henchPersonGender} {henchPersonPersonality} {henchPersonType} have been terrorising the city. The police are in their pocket and they have political ties too. Suggest that someone has to do something about them, and ask who is brave (or stupid) enough. Do not give a title or header. """)
                    .WithSelection("City")
                        .WithVariableName("city")
                        .WithNewChoice("New York")
                        .WithNewChoice("Los Angeles")
                        .WithNewChoice("Tokyo")
                        .WithNewChoice("Toronto")
                        .WithNewChoice("London")
                        .WithNewChoice("Berlin")
                        .WithNewChoice("Sydney")
                        .WithNewChoice("Paris")
                        .WithNewChoice("Hong Kong")
                        .WithNewChoice("Moscow")
                    .End()
                    .WithSelection("Villian Gender")
                        .WithVariableName("villainGender")
                        .WithNewChoice("Male")
                        .WithNewChoice("Female")
                        .WithNewChoice("Gender Non-binary")
                        .WithNewChoice("Trans Male")
                        .WithNewChoice("Trans Female")
                    .End()
                    .WithSelection("Villian Personality")
                        .WithVariableName("villianPersonality")
                        .WithNewChoice("Cruel")
                        .WithNewChoice("Philosophical")
                        .WithNewChoice("Vengeful")
                        .WithNewChoice("Unpredictable")
                        .WithNewChoice("Ostentatious")
                        .WithNewChoice("Silent")
                    .End()
                    .WithSelection("Villian Type")
                        .WithVariableName("villainType")
                        .WithNewChoice("Drug cartel captain")
                        .WithNewChoice("Special forces operator")
                        .WithNewChoice("Powerful hacker")
                        .WithNewChoice("Big-time gangster")
                        .WithNewChoice("Crooked Law Enforcement Officer")
                        .WithNewChoice("Ally turned enemy")
                    .End()

                    
                    .WithSelection("Henchperson Gender")
                        .WithVariableName("henchPersonGender")
                        .WithNewChoice("Male")
                        .WithNewChoice("Female")
                        .WithNewChoice("Gender Non-binary")
                        .WithNewChoice("Trans Male")
                        .WithNewChoice("Trans Female")
                    .End()
                    .WithSelection("Hench Person Personality")
                        .WithVariableName("henchPersonPersonality")
                        .WithNewChoice("Cruel")
                        .WithNewChoice("Philosophical")
                        .WithNewChoice("Vengeful")
                        .WithNewChoice("Unpredictable")
                        .WithNewChoice("Ostentatious")
                        .WithNewChoice("Silent")
                    .End()
                    .WithSelection("Hench Person Type")
                        .WithVariableName("henchPersonType")
                        .WithNewChoice("Body-builder")
                        .WithNewChoice("Militia captain")
                        .WithNewChoice("Cop (Fighty)")
                        .WithNewChoice("Pet Hacker")
                        .WithNewChoice("Lone Assassin")
                        .WithNewChoice("Street racer")
                    .End()
                .End()
                .WithCharacterSection()
                    .WithSelection("Personality")
                        .WithNewChoice("Wisecracking")
                        .WithNewChoice("Grave")
                        .WithNewChoice("Professional")
                        .WithNewChoice("Easy-going")
                        .WithNewChoice("Quiet")
                        .WithNewChoice("Hot-headed")
                    .End()
                    .WithSelection("Role")
                        .WithNewChoice("Ex-cop")
                        .WithNewChoice("Federal officer")
                        .WithNewChoice("Thief")
                        .WithNewChoice("Smuggler")
                        .WithNewChoice("Fixer")
                        .WithNewChoice("Ex-soldier")
                    .End()
                    .WithRandomAttributeSplitValue(3)
                        .WithRandomAttribute("Drive")
                        .WithRandomAttribute("Fight")
                        .WithRandomAttribute("Hack")
                .End()
            .End();
    }
}

