using System.Reflection;
using Kadense.RPG.Dice;

namespace Kadense.RPG.Games;

public partial class GamesFactory : GameBase
{
    [Game("Trashkin")]
    public GamesFactory Trashkin()
    {
        var attr = MethodInfo.GetCurrentMethod()!.GetCustomAttribute<GameAttribute>()!;
        return this
            .WithGame(attr.Name, attr.Description ?? "TBD Add Description")
                .WithCharacterSection()
                    .WithRandomAttribute("Audacious")
                    .WithRandomAttribute("Cunning")
                    .WithRandomAttribute("Big")
                    .WithRandomAttribute("Quick")
                    .WithSelection("Race")
                        .WithChoice("Raccoonkin")
                            .WithAttribute("Damage", "d6")
                            .WithAttribute("Audacious", "+1")
                            .WithAttribute("Cunning", "+1")
                            .WithSelection("Ability")
                                .WithNewChoice("Filthball", "Hurl a stinking orb of trash around")
                                .WithNewChoice("Trashstep", "Teleport between a pile of trash and another that you can see")
                                .WithNewChoice("Meld with trash", "Really get in there")
                                .WithNewChoice("Trash Glider", "Fashion a sort of paraglider out of stuff")
                                .WithNewChoice("Find Grot", "Divine the location of the nearest discarded erotica")
                                .WithNewChoice("Vorpal Tin Lid", "Gods, this thing is sharp!")
                            .End()
                        .End()
                        .WithChoice("Pigeonkin")
                            .WithAttribute("Damage", "d4")
                            .WithAttribute("Audacious", "+1")
                            .WithAttribute("Big", "-1")
                            .WithAttribute("You can", "Fly (a bit)")
                            .WithAttribute("You can also", "Smoke cigarettes")
                        .End()
                        .WithChoice("Ratboy")
                            .WithAttribute("Damage", "d4")
                            .WithAttribute("Quick", "+2")
                            .WithAttribute("You can", "Add quick damage to unaware targets")
                        .End()
                        .WithChoice("Foxfolk")
                            .WithAttribute("Damage", "d4")
                            .WithAttribute("Cunning", "+2")
                            .WithAttribute("You can", "Add quick damage to unaware targets")
                            .WithSelection("Ability")
                                .SetNumberToChoose(2)
                                .WithNewChoice("Filthball", "Hurl a stinking orb of trash around")
                                .WithNewChoice("Trashstep", "Teleport between a pile of trash and another that you can see")
                                .WithNewChoice("Meld with trash", "Really get in there")
                                .WithNewChoice("Trash Glider", "Fashion a sort of paraglider out of stuff")
                                .WithNewChoice("Find Grot", "Divine the location of the nearest discarded erotica")
                                .WithNewChoice("Vorpal Tin Lid", "Gods, this thing is sharp!")
                            .End()
                        .End()
                        .WithChoice("Half-Possum")
                            .WithAttribute("Damage", "d4")
                            .WithAttribute("Audacity", "+2")
                            .WithSelection("Ability")
                                .SetNumberToChoose(2)
                                .WithNewChoice("Animate Skellington", "Mainly small stuff like fish bones, etc")
                                .WithNewChoice("Apply used plaster", "Heal someone for d4 coppers")
                                .WithNewChoice("Play Undead", "Appear as a corpse, walking, or otherwise")
                                .WithNewChoice("Bone Armor", "Animate, then climb into a chicken carcass")
                                .WithNewChoice("Summon Trash Elemental", "It's just awful")
                                .WithNewChoice("Spit Hex", "Briefly blind or deafen a nearby foe")
                            .End()
                        .End()
                        .WithChoice("Goat-Girl")
                            .WithAttribute("Damage", "d6")
                            .WithAttribute("Big", "+1")
                            .WithAttribute("Audacious", "+1")
                            .WithAttribute("Charging in", "+1")
                            .WithAttribute("Ability", "Eat Tin Cans (and other stuff), it's your birthday!")
                            .WithSelection("Another Ability")
                                .WithNewChoice("Animate Skellington", "Mainly small stuff like fish bones, etc")
                                .WithNewChoice("Apply used plaster", "Heal someone for d4 coppers")
                                .WithNewChoice("Play Undead", "Appear as a corpse, walking, or otherwise")
                                .WithNewChoice("Bone Armor", "Animate, then climb into a chicken carcass")
                                .WithNewChoice("Summon Trash Elemental", "It's just awful")
                                .WithNewChoice("Spit Hex", "Briefly blind or deafen a nearby foe")
                            .End()
                        .End()
                    .End()
                    
                .End()
            .End();
    }
}

