using System.Reflection;

namespace Kadense.RPG.Models;

public partial class GamesFactory : GameFactoryBase
{
    [Game("Desert Bluffs", Description = @"#### Mid-1800s – Town Founding  
Desert Bluffs was founded in 1856, as a small trading outpost for pioneers heading west. It gained a foothold when local mineral deposits were discovered, attracting prospectors and settlers. The town became incorporated shortly after, ensuring it could manage law enforcement, infrastructure, and education for the growing population.
#### Late 1800s – The Boom Years
As the mining industry boomed, so did the economy. Desert Bluffs relied on placer mining (panning or sluicing for minerals like gold or silver found in sediment) in the nearby riverbeds and arid desert areas. By the late 1800s, the town reached a peak population of over 2,600, with many services, businesses, and even a modest local newspaper, the Desert Bluffs Chronicle. 
#### 1920s-1950s – Bust and Recovery Attempts
Over the following decades, the town's fortunes waned once the valuable minerals were exhausted. There was a significant population decline. Several recovery attempts were made, including agricultural projects, but none lasted. The town hung on through the Great Depression and World War II by relying on small farms and limited trade.
#### 1960s-1980s – Decline Sets In
By the 1960s, Desert Bluffs had lost any semblance of independent economy. The population had already dwindled by more than half, and many young adults left permanently for work, resulting in a stagnant community. The sheriff’s office saw reduced need as state law enforcement expanded.
#### 1990s-2000s – Population Exodus
Desert Bluffs became increasingly irrelevant. The K-12 school closed in 2014 due to dwindling student numbers. Most families chose to move to Lakeside, the next nearest town with school facilities and closer to Suncrest City. The closure of the school was a significant blow to the community, marking the end of Desert Bluffs as a thriving town. The sheriff’s office, already barely functional, was shuttered as well.
#### Present Day – A Sleepy Outpost
Desert Bluffs now exists as a sleeper town, with no more than a few hundred residents remaining. A few key locations, like the library and local church, still serve the remaining population, but most businesses have long since closed or moved to Suncrest City. Many houses sit empty, waiting to be demolished or turned into student housing. Despite its dwindling population, Desert Bluffs retains a sense of stubborn resilience. Some residents hold onto the quiet way of life, and a growing interest from Suncrest City University’s cultural projects has breathed a small but notable revitalisation into parts of the town. ")]
    public GamesFactory DesertBluffs()
    {
        var attr = MethodInfo.GetCurrentMethod()!.GetCustomAttribute<GameAttribute>()!;
        return this
            .WithGame(attr.Name, attr.Description!)
                .WithIsDynamic()
                .WithImagePath("/assets/desert-bluffs/the-road.png")
                .WithLocation()
                    .WithName("American Spirit Bar")
                    .WithDescription(@"The American Spirit Bar is a long low single-story building with a distinctive look from the thick adobe walls that hold out the desert heat during the day and keep out the chill at night. 

The ochre-coloured plaster, both inside and out, has been carefully maintained over the years. The wooden window and door frames, darkened and smoothed with age and varnish, contrast with the sunbaked walls.

Outside the building there is a small shelf area where patrons may clearly gather with their drinks.")
                    .WithImagePath("/assets/desert-bluffs/american-spirit/Exterior.png")
                    .WithArea()
                        .WithName("Main Bar")
                        .WithImagePath("/assets/desert-bluffs/american-spirit/Interior.png")
                        .WithDescription(@"Inside the building the floor is paved with broad stone flags, cool underfoot even in the heat of summer, worn down by the passage of time and passing feet alike. A long, polished bar stretches across one side of the main room. Sturdy wooden stools line the bar. 

To the other side, there are areas subdivided by wooden framing, providing table arrangements not dissimilar to booths in that they provide a sense of intimacy for small groups.  

A large flag hangs on one wall, marking the tavern's role as a VFW bar, and beneath it, a display of old photos and military memorabilia tells the stories of those who served. It's not just decoration—it's a reminder, a connection, a space of respect. Near the flag and the display area, there is a door marked with a sign 'FOB-DB' attached.

There are no door frame lips and though the area is clearly often busy from the number of tables arranged within, wide pathways ensure ease of movement between them, and at the back there is clear signage for several disability-friendly, gender-neutral, individual toilet cubicles. There is a door marked 'STAFF ONLY' near the toilets.

There are shelves clearly visible with several packs of cards, boxes of dominos and other small table games that look well used.

#### Opening Hours
* Monday – Thursday: 3:00 PM – 11:00 PM
* Friday – Saturday: 2:00 PM – 1:00 AM
* Sunday: 12:00 PM – 10:00 PM

##### Notes
Carlos works the most regular hours since he’s the primary hired bartender.
Thomas and Jamal take turns covering management shifts and ensuring a co-owner is always present, especially on busier nights.
Keisha works infrequent evenings, as she works a part time job weekday morning at the Town Hall and parents the children. Bly’s children are grown and Bly volunteers ad-hoc at the cultural centre so has more time to devote to the business.

##### Behind the Bar

###### Monday - Thursday

Shift | Time | Who
-|-|-
Early | 3:00 PM – 7:00 PM | Carlos Rivera and either Thomas Yazzie or Jamal Freeman (50% chance)
Late shift | 7:00 PM – 11:00 PM | Either Thomas Yazzie or Jamal Freeman (50% chance depending on who was in earlier) and either Bly Yazzie (75% chance) or Keisha Freeman (50% chance)

###### Friday - Saturday

| Shift | Time | Who |
| --- | --- | --- |
| Afternoon shift | 2:00 PM – 6:00 PM | Carlos Rivera and Bly Yazzie |
| Evening shift | 6:00 PM – 10:00 PM | Thomas Yazzie and Keisha Freeman |
| Late shift | 10:00 PM – 1:00 AM | Jamal Freeman and Carlos Rivera |

###### Sunday

| Shift | Time | Who |
| --- | --- | --- |
| Early shift | 12:00 PM – 5:00 PM | Thomas Yazzie and Bly Yazzie |
| Evening shift | 5:00 PM – 10:00 PM | Jamal Freeman |

Jacy Yazzie may be found sometimes at this location during the daytime. Jacy is a key NPC as he works night shifts as a watchman at Self Storage Solutions. He does not witness any disturbances at Self Storage Solutions as he is protected by his mother’s faith (and protective design tattoo) on his chest.

Charlie ‘Brewski’ Thompson can be found at this location typically during the later shifts but is never there until closing time as he is cut off at the bar after two beers due to his alcoholism. After he has drunk his two beers, he goes back to his nearby home to drink. Brewski isn’t fond of being out at night and will be distressed if he misses sunset. 
Brewski was previously the night watchman at Self Storage Solutions, and he will tell Player Characters about strange things happening while he did his rounds: he describes the automatic sensors that know when the rounds are walked. The sensors would trigger as though someone was walking backwards and forwards in one of the corridors, though it was dark on the CCTV and the night vision mode showed there was no heat source. He describes falling asleep in the office and waking up to find a dark shadowy figure stood over him, draining him of all that was good and true.
These repeated encounters made him more and more fearful.")
                        .WithId("main-bar")
                    .End()
                    .WithArea()
                        .WithName("Storage Room")
                        .WithDescription(" A space for storing extra bottles of alcohol, kegs, bar snacks, cleaning supplies, and general stock. Accessed via a door behind or near the bar.")
                        .WithId("storage-room")
                    .End()
                    .WithArea()
                        .WithName("Office")
                        .WithDescription("A small room for the co-owners, Thomas and Jamal, to handle paperwork, manage orders, and deal with finances. Has a desk, a filing cabinet, and a couple of chairs.")
                        .WithId("office")
                    .End()
                    .WithArea()
                        .WithName("Break room")
                        .WithDescription("A modest space with a table, chairs, and maybe a small kitchenette (microwave, coffee maker, and a fridge) where bartenders can take a break.")
                        .WithId("break-room")
                    .End()
                    .WithArea()
                        .WithName("Utility Room")
                        .WithDescription("A space for janitorial supplies, a mop sink, and plumbing access")
                        .WithId("utility-room")
                    .End()
                    .WithArea()
                        .WithName("FOB-DB")
                        .WithDescription(@"The FOB-DB (Forward Operating Base – Desert Bluffs) is a small side room where veterans can gather privately.
* Walls are decorated with military memorabilia, including framed photos of local veterans, patches, old unit insignias, and maybe a shadow box of medals.
* An American flag and a POW/MIA flag hang prominently on one wall.
* A large wooden table with sturdy chairs sits in the centre, ideal for meetings, casual card games, or just catching up.
* A small bookshelf, stocked with military history books, donated paperbacks, and some field manuals.
* A locker holding things like spare hats, cigars, board games, or donations for veterans in need.
* A well-worn coffee station: always hot, with a selection of mugs, some featuring old unit logos or inside jokes.
* A whiteboard used for meeting notes, event planning, or just humorous doodles and inside jokes.
* A softer seating area: a couch or a couple of old recliners where vets can sit back and talk in a more relaxed setting.")
                        .WithId("fob-db")
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Map of Desert Bluffs")
                            .WithImagePath("/assets/desert-bluffs/items/map.jpg")
                            .WithDescription("A map of the local area provided by the local government for distribution to tourists.")
                            .WithAttachment()
                                .WithName("Map")
                                .WithDescription("A map of the local area")
                                .WithPath("/assets/desert-bluffs/items/map.jpg")
                            .End()
                            .WithId("map")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Thomas Yazzie")
                            .WithImagePath("/assets/desert-bluffs/Thomas-Yazzie.png")
                            .WithFactBasedSummary("Thomas Yazzie is in his 60s. He the co-owner of the American Spirit Bar. He often speaks out about his lived experience of attempted erasure, advocating for Indigenous rights and cultural preservation. Father to Bly, Grandfather to Jacy and Lily.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Tashké")
                            .WithAgeRange("60s")
                            .WithId("thomas-yazzie")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Bly Yazzie")
                            .WithImagePath("/assets/desert-bluffs/Bly-Yazzie.png")
                            .WithFactBasedSummary("Bly Yazzie is in her 40s. She is the daughter of Thomas Yazzie and is actively involved in the Tashké cultural centre at the library. She is the mother of Jacy and Lily Yazzie.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Tashké")
                            .WithAgeRange("40s")
                            .WithId("bly-yazzie")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jamal Freeman")
                            .WithImagePath("/assets/desert-bluffs/Jamal-Freeman.png")
                            .WithFactBasedSummary("Jamal Freeman is in his 40s. He is a retired US Army Sergeant Major. He is married to Keisha Freeman and is the father of Malik and Aaliyah. He co-owns the American Spirit Bar with Thomas Yazzie.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("African American")
                            .WithAgeRange("40s")
                            .WithId("jamal-freeman")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Aaliyah Freeman")
                            .WithImagePath("/assets/desert-bluffs/Malik-and-Aaliyah-Freeman.png")
                            .WithFactBasedSummary("Aaliyah Freeman is 6 years old and the daughter of Jamal and Keisha Freeman. He attends school in nearby Lakeview, along with other children from Desert Bluffs.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("African American")
                            .WithAge(6)
                            .WithId("aaliyah-freeman")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Malik Freeman")
                            .WithImagePath("/assets/desert-bluffs/Malik-and-Aaliyah-Freeman.png")
                            .WithFactBasedSummary("Malik Freeman is 8 years old and the son of Jamal and Keisha Freeman. He attends school in nearby Lakeview, along with other children from Desert Bluffs.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("African American")
                            .WithAge(8)
                            .WithId("malik-freeman")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Carlos Rivera")
                            .WithImagePath("/assets/desert-bluffs/Carlos-Rivera.png")
                            .WithFactBasedSummary("Carlos Rivera is in his 20s. He is a bartender at the American Spirit Bar, where he manages evening shifts and serves both veterans and locals. Married to Molly Rivera, Carlos handles the bar’s day-to-day operations and is known for keeping things running efficiently.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Hispanic/Latino")
                            .WithAgeRange("20s")
                            .WithId("carlos-rivera")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Charlie 'Brewski' Thompson")
                            .WithImagePath("/assets/desert-bluffs/Charlie-Thompson.png")
                            .WithFactBasedSummary("Charlie \"Brewski\" Thompson is in his 50s. He is a former night watch officer at Storage Solutions who lost his job and is now unemployed. He is an alcoholic who drinks both at home and at the American Spirit Bar.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithDiversityFlag("Alcoholic")
                            .WithAgeRange("50s")
                            .WithId("charlie-thompson")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Bob Anderson")
                            .WithImagePath("/assets/desert-bluffs/Bob-Anderson.png")
                            .WithFactBasedSummary("Bob Anderson is in his 70s. He is a retired Marine Private First Class. He served in both the Vietnam War and Desert Storm, sustaining shrapnel wounds from a grenade explosion during the Gulf War. He is a regular at the American Spirit Bar.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("50s")
                            .WithId("bob-anderson")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jim Harris")
                            .WithImagePath("/assets/desert-bluffs/Jim-Harris.png")
                            .WithFactBasedSummary("Jim Harris is in his 50s. He is a retired Marine Private. He served in Panama during Operation Just Cause and in Bosnia during Operation Joint Endeavour, where he suffered hearing loss due to exposure to noise exposure. He is a regular at the American Spirit Bar.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithDiversityFlag("Deaf, uses ASL")
                            .WithAgeRange("50s")
                            .WithId("jim-harris")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jimmy Turner")
                            .WithImagePath("/assets/desert-bluffs/Jimmy-Turner.png")
                            .WithFactBasedSummary("Jimmy Turner is in his 70s. He is a retired Marine Staff Sergeant. He served in both the Vietnam War and Desert Storm, sustaining a knee injury during a firefight in Vietnam. He is a regular at the American Spirit Bar.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("70s")
                            .WithId("jimmy-turner")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Sam Mitchell")
                            .WithImagePath("/assets/desert-bluffs/Sam-Mitchell.png")
                            .WithFactBasedSummary("Sam Mitchell is in her 40s. She is a retired Gunnery Sergeant in her late 40s. She served in the Iraq War during Operation Iraqi Freedom and in Kosovo during Operation Joint Guardian.  She is a regular at the American Spirit Bar.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("White")
                            .WithAgeRange("40s")
                            .WithId("sam-mitchell")
                        .End()
                    .End()
                    .WithId("american-spirit")
                    .WithAnnotation("1")
                .End()
                .WithLocation()
                    .WithName("Desert Bites Diner")
                    .WithImagePath("/assets/desert-bluffs/desert-bites/Exterior.png")
                    .WithDescription(@"The Desert Bites Diner serves as a vital social hub for Desert Bluffs, offering a warm atmosphere where locals gather to share stories, enjoy a meal, and catch up on the latest town gossip. It’s a simple, no-frills establishment that reflects the town's character and resilience.
* The diner features a classic Americana style, with a neon sign above the building that reads “Desert Bites Diner.”
* There is a small parking lot, often filled with the cars of regular patrons.

#### Clientele
* The diner is particularly popular among the elderly residents of Desert Bluffs, who come in regularly for breakfast and dinner.
* It’s usual to see familiar faces engaged in conversation over cups of coffee or hearty meals.
* The menu prices are comfortably cheap and affordable, business is good.
* Harry and Gene have a romantic table for 2 most afternoons after they close their store.")
                    .WithArea()
                        .WithName("Main Restaurant")
                        .WithDescription(@"* Upon entering, guests are greeted by the smell of good food and fresh coffee. 
* There's a good quality small Bluetooth speaker on the counter, playing a mixture of music from classic British tunes to music of African and Indigenous origin.
* The interior is modest, well worn vinyl booths and tables surrounding a long counter. 
* The diner has a payphone near the entrance.")
                        .WithImagePath("/assets/desert-bluffs/desert-bites/Interior.png")
                        .WithId("main-restaurant")
                    .End()
                    .WithArea()
                        .WithName("Kitchen")
                        .WithDescription(@"* The diner has a small kitchen where one dedicated cook handles most of the meal prep.
* The two owners pitch in during non-peak hours, serving sandwiches and lighter fare.
* The menu is limited but always includes a meat option and a vegetarian option, ensuring that there’s something for everyone.")
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Betty White")
                            .WithImagePath("/assets/desert-bluffs/Betty-White.png")
                            .WithFactBasedSummary("Betty White is in her 70s, of Kenyan Black origin, and is in a relationship with Lizzy Black. She is a co-owner of the Desert Bites Diner. Lives with Lizzy in the House Behind the Diner.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Black African")
                            .WithDiversityFlag("Lesbian")
                            .WithAgeRange("70s")
                            .WithId("betty-white")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Lizzy Black")
                            .WithImagePath("/assets/desert-bluffs/Lizzy-Black.png")
                            .WithFactBasedSummary("Lizzy Black is in her 70s, of White British origin, and is in a relationship with Betty White. She is a co-owner of the Desert Bites Diner. Lives with Lizzy in the House Behind the Diner.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("White")
                            .WithDiversityFlag("Lesbian")
                            .WithAgeRange("70s")
                            .WithId("lizzy-black")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Lily Yazzie")
                            .WithImagePath("/assets/desert-bluffs/Lily-Yazzie.png")
                            .WithFactBasedSummary("Lily Yazzie is 19 years old and works as wait staff at the Desert Bites Diner. She is also pursuing a part-time university degree in Environmental Science. Lily is the daughter of Bly Yazzie and was assigned male at birth but is a trans woman.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Tashké")
                            .WithDiversityFlag("Transgender")
                            .WithAge(19)
                            .WithId("lily-yazzie")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Scott Graham")
                            .WithImagePath("/assets/desert-bluffs/Scott-Graham.png")
                            .WithFactBasedSummary("Scott Graham is a White man in his early 50s with a buzzcut and stubble. Born and raised in Desert Bluffs, he moved back after a failed relationship and layoff from a chef job in Suncrest. He’s lived in a trailer on the town’s edge for 20 years and has been a dependable fixture at Desert Bites Diner since taking a summer contract years ago.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("50s")
                            .WithId("scott-graham")
                        .End()
                    .End()
                    .WithItemLink("map")
                    .WithItemLink()
                        .WithItem()
                            .WithName("Desert Bites Diner Menu")
                            .WithImagePath("/assets/desert-bluffs/items/Desert-Bites-Diner-Menu.png")
                            .WithAttachment()
                                .WithName("The Menu")
                                .WithDescription("A PDF version of the Desert Bites Diner Menu")
                                .WithPath("/assets/desert-bluffs/items/Desert-Bites-Diner-Menu.pdf")
                            .End()
                            .WithAttachment()
                                .WithName("Monday Specials")
                                .WithDescription("Specials on a Monday")
                                .WithPath("/assets/desert-bluffs/items/Desert-Bites-Diner-Menu/specials-Monday.png")
                            .End()
                            .WithAttachment()
                                .WithName("Tuesday Specials")
                                .WithDescription("Specials on a Tuesday")
                                .WithPath("/assets/desert-bluffs/items/Desert-Bites-Diner-Menu/specials-Tuesday.png")
                            .End()
                            .WithAttachment()
                                .WithName("Wednesday Specials")
                                .WithDescription("Specials on a Wednesday")
                                .WithPath("/assets/desert-bluffs/items/Desert-Bites-Diner-Menu/specials-Wednesday.png")
                            .End()
                            .WithAttachment()
                                .WithName("Thursday Specials")
                                .WithDescription("Specials on a Thursday")
                                .WithPath("/assets/desert-bluffs/items/Desert-Bites-Diner-Menu/specials-Thursday.png")
                            .End()
                            .WithAttachment()
                                .WithName("Friday Specials")
                                .WithDescription("Specials on a Friday")
                                .WithPath("/assets/desert-bluffs/items/Desert-Bites-Diner-Menu/specials-Friday.png")
                            .End()
                            .WithAttachment()
                                .WithName("Weekend Specials")
                                .WithDescription("Specials on a Weekend")
                                .WithPath("/assets/desert-bluffs/items/Desert-Bites-Diner-Menu/specials-Weekend.png")
                            .End()
                            .WithId("diner-menu")
                        .End()
                    .End()
                    .WithId("desert-bites")
                    .WithAnnotation("3")
                .End()
                .WithLocation()
                    .WithName("Desert View")
                    .WithImagePath("/assets/desert-bluffs/desert-view/Exterior.png")
                    .WithDescription(@"Desert View is a single-storey, L-shaped building set against the arid backdrop of Desert Bluffs. Its beige stucco walls and flat roof reflect a functional, institutional design typical of care facilities. The entrance features wide, automatic sliding glass doors designed for accessibility. Windows are large and double-glazed, with sheer curtains visible from outside. A small, neatly maintained garden courtyard sits to one side, offering a quiet outdoor space. 
The building's exterior is clean but unadorned, with minimal signage and no visible branding or logos. The atmosphere is calm and professional, giving little away beyond its purpose as a place of care.
There's plenty of parking outside, with several cars already parked in the area marked for staff use only.

#### Public Visiting Hours
Visiting is permitted everyday on the following schedule:

| Morning | Afternoon |
| --- | --- |
| 10:00 AM – 12:00 PM | 2:00 PM – 5:00 PM |


#### Visitor Rules
* Visitors are asked to sign in at reception upon arrival.
* Visits outside these hours may be arranged in advance for medical or compassionate reasons.
* Group visits and children under 12 should be approved beforehand to ensure a calm environment for all residents.

#### Staffing
* Nurses (4 total): Rotating presence, provide medical monitoring and medication rounds.
* Care Aides (8 total): Assist with mobility, hygiene, and daily routines for residents.
* Occupational Therapist (1 part-time): Supports residents with cognitive/motor rehab.
* Cleaner/Maintenance (2 total): Keep the facility clean, handle minor repairs.
* Reception/Admin (1 full-time, 1 part-time): Manage calls, paperwork, and sign-ins.
* Kitchen Staff (2 total): Prepare and serve basic meals; not elaborate catering. Note that residents who are safe to do so are welcome to eat at the Desert Bites Diner under a standing contract with Desert View.


#### Clues
##### Tidal Dynamics Call & Response
Desert View is a Tidal Dynamics facility, but this is kept very, very low key. The call and response phrase ‘uncommon paths’ coupled with ‘light on’ will unlock more information from the shift managers about some of their guests.")
                    .WithArea()
                        .WithName("Lobby")
                        .WithDescription(@"The lobby is clean and plainly furnished, with smooth vinyl flooring and neutral-coloured walls. A reception desk sits directly ahead, separated by a low partition and fitted with a wall-mounted sign-in tablet. A few armchairs are arranged along the wall for waiting visitors, and a hand sanitiser dispenser is positioned near the entrance. Fluorescent ceiling lights provide consistent illumination. There is a faint antiseptic smell, and the overall impression is one of quiet order and minimal clutter.")
                    .End()
                    .WithArea()
                        .WithName("Shared Living Area")
                        .WithDescription(@"Beyond the lobby, the shared living space opens into a modest, open-plan room. Several upholstered armchairs and small sofas are arranged in a loose circle around a low table. A bookshelf near the wall holds large-print books, a few puzzles, and neatly stacked magazines. Framed landscape prints hang on the walls, and a wide window lets in natural light through sheer curtains. The atmosphere is subdued and quiet, intended more for calm routine than social activity. There are no personal items visible.")
                        .WithImagePath("/assets/desert-bluffs/desert-view/Interior-Living-Area.png")
                    .End()
                    .WithArea()
                        .WithName("Bedrooms")
                        .WithDescription(@"Each bedroom is private and simply furnished.
A single, hospital-style bed sits near the centre of the room, equipped with adjustable height settings and safety rails. Beside it, a small table holds a reading lamp and a lockable drawer for personal items. Wardrobes provides storage space. The window is dressed with sheer curtains and blackout blinds. The walls are painted in neutral tones, and a modern flat screen television is typically mounted opposite the bed.
The attached ensuite bathroom includes a walk-in shower, grab rails, and non-slip flooring. The room is quiet, functional, and free of personal decoration unless added by the resident or their family.")
                        .WithImagePath("/assets/desert-bluffs/desert-view/Interior-Bedroom.png")
                    .End()
                    .WithItemLink("map")
                    .WithItemLink()
                        .WithItem()
                            .WithName("Letter From Raj Patel")
                            .WithImagePath("/assets/desert-bluffs/items/Letter-from-Raj-Patel.png")
                            .WithAttachment()
                                .WithName("The Letter")
                                .WithPath("/assets/desert-bluffs/items/Letter-from-Raj-Patel.png")
                            .End()
                            .WithId("letter-from-raj-patel")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Drawing found in Raj Patel's room")
                            .WithImagePath("/assets/desert-bluffs/items/raj-drawing.png")
                            .WithAttachment()
                                .WithName("The Drawing")
                                .WithPath("/assets/desert-bluffs/items/raj-drawing.png")
                            .End()
                            .WithId("raj-drawing")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Raj Patel's Walking Stick")
                            .WithDescription(@"Appearance: A sturdy wooden staff, smooth and polished to a warm reddish-brown glow. Carvings of Hanuman’s emblem—a stylised monkey face or mace—are etched near the top, along with Sanskrit inscriptions invoking strength, protection, and devotion. The staff feels balanced and weighty in the hand, as if crafted with care and reverence.
Magical Properties: Strength of Hanuman: When wielded, the staff grants the bearer enhanced physical strength and endurance, echoing Hanuman’s legendary might.
Protector’s Blessing: The staff offers a spiritual shield, calming the wielder’s mind and bolstering courage against fear and despair.
Channel for Service: The staff amplifies the wielder’s ability to protect and serve others, encouraging acts of selflessness and honour.
Silent Guidance: When the bearer is uncertain or lost, the staff gently vibrates or hums, as if guiding them toward their purpose or next step.

Placement and Condition: The staff rests carefully beside Raj’s bed, wrapped in a cloth embroidered with sacred symbols. It shows signs of long use but is well cared for, with faint scratches hinting at battles fought or trials endured. The inscriptions are slightly worn, suggesting Raj’s devotion endured until the end.")
                            .WithImagePath("/assets/desert-bluffs/items/raj-walking-stick.png")
                            .WithAttachment()
                                .WithName("The Walking Stick")
                                .WithPath("/assets/desert-bluffs/items/raj-walking-stick.png")
                            .End()
                            .WithId("raj-walking-stick")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Malcolm Tetherwall")
                            .WithDescription(@"Malcolm Tetherwall is a deeply frail centenarian, his once-strong presence now a whisper of what it used to be. Despite his age, his mind remains sharp, and his voice, though weakened, still carries the weight of decades of broadcasting. He spends most of his days sleeping, tucked away in the corner of Desert View’s retirement complex, but on the rare occasions he wakes, his sharp eyes gleam with memories of the past.
                            
#### Timeline of Malcolm Tetherwall’s Life and Radio Station (linked to K5N5 Sunset Sounds):
* 1925: Born in Desert Bluffs.
* 1943: Enlists in the military in World War II. Returns after the war to settle in Desert Bluffs.
* 1950: Starts working at a local radio station, doing small voiceovers and community spots.
* 1955: Begins hosting his own show, ""Sunset Sounds,"" a nightly program with local music, news, and community updates. The show becomes popular for its laid-back, personal tone.
* 1960-1980: Years of growth for K5N5 Sunset Sounds. Malcolm’s show grows in popularity as he becomes a staple of Desert Bluffs’ nightly routine. Known for his calm, reflective voice, he offers a mix of personal anecdotes, local news, and moral reflections. He’s seen as a fatherly figure in the community.
* 1986: Broadcasts the opinion piece ""Shadows in the Heartland"", a reflection on the changes and losses in the town. This marks the beginning of a gradual decline in the town’s spirit, though Malcolm remains optimistic.
* 1990: Malcolm’s health begins to deteriorate as he reaches 65, but he still hosts the show from time to time. He starts sleeping more often, and the show begins to feel more like a shadow of its former self.
* 1993: K5N5 Sunset Sounds closes due to financial struggles. The station’s equipment is outdated, and the rise of more modern media outlets, including television and FM radio, leads to its decline. In his own words: “We kept trying, but the town... the people, they stopped listening. I’d like to think we went out with dignity, but that’s not always the way things go.” Malcolm moved into Desert View at age 68. 
* His health continued to decline, and he is now 100 years old.")
                            .WithImagePath("/assets/desert-bluffs/Malcolm-Tetherwall.png")
                            .WithFactBasedSummary("Malcolm Tetherwall is 100 years old and a resident at Desert View since 1993. He was the Sunset Sounds radio host before he retired and the station closed.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithDiversityFlag("Gay")
                            .WithAge(100)
                            .WithId("malcolm-tetherwall")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Eloise Rainer")
                            .WithDescription(@"A calm, professional woman in her early 60s with a background in occupational therapy. She manages schedules, oversees medical coordination, and handles all visitor enquiries during the day. Polite but brisk, she expects efficiency and keeps a tight ship. She is also a highly trained and experienced Tidal Dynamics Professional.

***Hello, this is Eloise Rainer. I’m one of the managers here at Desert View, in Desert Bluffs. We have a resident here, Mr Raj Patel. I’m sorry to let you know that Raj has reached the end of his lifespan with us here on earth – he is in the process of dying. He may not have long left, and he has asked us to reach out to you. He has walked an uncommon path through life and wishes you to be with him at the end.***")
                            .WithImagePath("/assets/desert-bluffs/Eloise-Rainer.png")
                            .WithFactBasedSummary("Eloise Rainer is in her early 60s and the day shift manager at Desert View. She exudes quiet authority and rarely raises her voice. Formerly an occupational therapist, she transitioned to management after thirty years in hospital-based care. She has a reputation for running a steady ship, prioritising consistency and dignity in patient handling.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Black")
                            .WithDiversityFlag("Disabled (Uses a walking stick as a mobility aid)")
                            .WithAgeRange("60s")
                            .WithId("eloise-rainer")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Adam Rios")
                            .WithImagePath("/assets/desert-bluffs/Adam-Rios.png")
                            .WithDescription("A quiet, observant man in his late 40s with prior experience in psychiatric support work. He handles overnight admissions, security protocols, and emergency contact. He’s slower to speak than Rainer but tends to remember small details. Slightly overworked, often seen with a thermos. He is also a highly trained and experienced Tidal Dynamics Professional.")
                            .WithFactBasedSummary("Adam Rios is in his early 40s and the night shift manager at Desert View. He typically wears pressed scrubs under a zip-up hoodie and keeps a thermos with him at most times. A small St. Christopher medallion hangs from a leather cord around his neck. Quiet, observant, and warm-voiced. He takes his time before answering and rarely interrupts. His presence is reassuring, especially to residents prone to confusion or distress at night.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Latino")
                            .WithDiversityFlag("PTSD")
                            .WithAgeRange("40s")
                            .WithId("adam-rios")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jasmine 'Jazz' Carter")
                            .WithImagePath("/assets/desert-bluffs/Jazz-Carter.jpg")
                            .WithFactBasedSummary("See handout for Jazz Carter")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Black")
                            .WithAgeRange("70s")
                            .WithId("jazz-carter")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Edna Mallory")
                            .WithImagePath("/assets/desert-bluffs/Edna-Mallory.png")
                            .WithFactBasedSummary(@"#### 1939
Born in Desert Bluffs

#### 1960s–early 2000s
Worked as a teacher at Vista School (K–12), teaching English and Social Studies

#### 1986
One of Luke Salcedo’s teachers during his final year
* Remembers Luke as bright, quiet, and artistic
* Knows he was bullied by classmates for being part Native American and for wearing his hair long
* Recalls him becoming withdrawn shortly before disappearing
* Her recollection of possible links between Luke and Father Jack is inaccurate — she’s misremembering or misattributing the timeline due to age and stress

#### 2014 
Retires around the time Vista School closes

#### Late 2010s
Moves into Desert View retirement facility

#### Campaign Present
* Reports seeing shadows in her room and hallway
* Believes she is being watched, but won’t speak openly unless the players gain her trust
* Feels safe only because of salt lines she has placed at her door and under her bed
* If players ask about the school or mention Luke, she shares what she remembers — no records, only her story")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Black")
                            .WithDateOfBirth(new DateTime(1939, 4, 5))
                            .WithId("edna-mallory")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Father Kevin Flowers")
                            .WithImagePath("/assets/desert-bluffs/Father-Kevin-Flowers.png")
                            .WithFactBasedSummary("Father Kevin Flowers is a retired priest in his late 60s with a calm but weary presence. Having served the local parish for over four decades, Kevin is known for his gentle voice and thoughtful counsel, though recent years have seen him more withdrawn, reflecting on the changes in Desert View. His appearance is marked by silver hair, kind eyes behind simple glasses, and a habit of wearing plain, comfortable clothes rather than formal clerical attire since retirement.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("60s")
                            .WithId("father-flowers")
                        .End()
                    .End()
                    .WithId("desert-view")
                    .WithAnnotation("4")
                .End()
                .WithLocation()
                    .WithName("Gas'n'go")
                    .WithDescription(@"A relatively modern outpost of everyday convenience, the Gas'n'Go sits on the edge of Desert Bluffs like it could be anywhere—or nowhere. The main building is a low, cinderblock rectangle with stark white walls and red trim, fronted by a wide metal overhang that shelters four fuel pumps. The signage is minimal but clean, illuminated by buzzing LED strips that never quite stop flickering.
To one side sits a larger-than-expected service garage, a metal structure painted to match the station. With four wide shutter doors, it suggests either a heyday the town’s long outgrown—or a purpose beyond simple repairs.
Inside, the shop is sparse but tidy: a few shelves of snacks, fridges humming in the back, a tired coffee machine, and a small counter with a good view of the forecourt. Security cameras are obvious. A locked door marked “Staff Only” leads somewhere behind the drinks fridges.")
                    .WithImagePath("/assets/desert-bluffs/gas-n-go/Exterior.png")
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Lucia Morales")
                            .WithImagePath("/assets/desert-bluffs/Lucia-Morales.png")
                            .WithFactBasedSummary("Lucia Morales is in her 20s. She is a skilled mechanic who works closely with university students during their hands-on training sessions. She is practical, tough, and enjoys teaching. Her role includes assisting with both the Gas'n'Go business and the university’s projects, ensuring that students gain valuable practical experience while helping keep the workshop running smoothly.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Hispanic/Latino")
                            .WithAgeRange("30s")
                            .WithId("lucia-morale")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Paul 'PJ' Johnson")
                            .WithImagePath("/assets/desert-bluffs/Paul-Johnson.png")
                            .WithFactBasedSummary("Paul \"PJ\" Johnson is in his late 30s. He works as the night shift attendant at the Gas’n’Go. PJ is calm and reliable, ensuring everything runs smoothly during the late hours. He was born and raised in Arizona.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("African American")
                            .WithDiversityFlag("Neurodivergent (Autism Spectrum)")
                            .WithAgeRange("30s")
                            .WithId("paul-johnson")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("David Inoue")
                            .WithImagePath("/assets/desert-bluffs/David-Inoue.png")
                            .WithFactBasedSummary("David Inoue is in his late 20s. He works as a workshop assistant mechanic at the Gas’n’Go, where he assists both the family business and the university’s automotive training projects. David is of Japanese American heritage, and his family originates from Tokyo, Japan, though he was born and raised in California.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Asian Japanese")
                            .WithAgeRange("20s")
                            .WithId("david-inoue")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jordan Reyes")
                            .WithImagePath("/assets/desert-bluffs/Jordan-Reyes.png")
                            .WithFactBasedSummary("Jordan Reyes is in their late 20s. They work as a mechanic at the Gas’n’Go, assisting with both the daily operations of the shop and university-affiliated projects. They play a key role in helping manage the workload at the garage while also guiding students during their hands-on training. Jordan is originally from a small town in the Southwest United States.")
                            .WithPronouns("They/Them")
                            .WithDiversityFlag("Mixed Race (White/Hispanic)")
                            .WithDiversityFlag("Gender Non-Binary")
                            .WithAgeRange("20s")
                            .WithId("jordan-reyes")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jake Kowalski")
                            .WithImagePath("/assets/desert-bluffs/Jake-Kowalski.png")
                            .WithFactBasedSummary("Jake Kowalski is in his 30s and is the owner of the Gas’n’Go. He runs the business with help from his family and university staff through a lease arrangement with Suncrest University. As the business contracted over the years, Jake made a deal to lease out unused workshops for university training programs, ensuring the family business stays afloat.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("30s")
                            .WithId("jake-kowalski")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Ellen Kowalski")
                            .WithImagePath("/assets/desert-bluffs/Ellen-Kowalski.png")
                            .WithFactBasedSummary("Ellen Kowalski is in her 60s and helps out at the Gas’n’Go, which is run by her son, Jake Kowalski. She supports her husband, Jacob Kowalski, who has early-onset Parkinson's. Ellen is also an active member of the Catholic church and is often busy with community events.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("White")
                            .WithAgeRange("60s")
                            .WithId("ellen-kowalski")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jacob Kowalski")
                            .WithImagePath("/assets/desert-bluffs/Jacob-Kowalski.png")
                            .WithFactBasedSummary("Jacob Kowalski is in his late 60s and has early-onset Parkinson's. He emigrated from Poland and wants to remain in the property he's owned since arriving in America as long as he can maintain his independence. He occasionally helps out at the Gas’n’Go with his wife, Ellen, and son, Jake.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithDiversityFlag("Early onset Parkinsons")
                            .WithAgeRange("60s")
                            .WithId("jacob-kowalski")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Evelyn \"Evie\" Martinez")
                            .WithImagePath("/assets/desert-bluffs/Evelyn-Martinez.png")
                            .WithFactBasedSummary("Dr. Evelyn \"Evie\" Martinez is in her late 40s. She holds a doctorate in Mechanical Engineering with a focus on Automotive Engineering. She oversees the automotive training program at the Gas'n'Go workshops, mentoring students from Suncrest University. Dr. Martinez is originally from New Mexico.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Hispanic/Latino")
                            .WithAgeRange("40s")
                            .WithId("evelyn-martinez")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Charlie Hoskin")
                            .WithImagePath("/assets/desert-bluffs/Charlie-Hoskin.png")
                            .WithFactBasedSummary("Charlie Hoskin is in his early 30s and works as a mechanic at the Gas’n’Go. He is of Tashké heritage and previously worked part-time at the Tashké Cultural Centre. Charlie specialises in off-road and heavy-duty vehicles and plays a key role in helping manage the workload at the garage. He is originally from Desert Bluffs.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Tashké")
                            .WithAgeRange("30s")
                            .WithId("charlie-hoskin")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Tina Wallace")
                            .WithImagePath("/assets/desert-bluffs/Tina-Wallace.png")
                            .WithFactBasedSummary("Tina Wallace is in her mid-20s and works as a cashier at the Gas’n’Go. She handles customer transactions and helps keep the shop organised. Tina is originally from Desert Bluffs and is currently working on her GED courses at Lakeview High School in the evenings.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("White")
                            .WithAgeRange("20s")
                            .WithId("tina-wallace")
                        .End()
                    .End()
                    .WithItemLink("map")
                    .WithItemLink()
                        .WithItem()
                            .WithName("Gas'n'Go Opening Hours")
                            .WithImagePath("/assets/desert-bluffs/items/Gas-n-Go-Opening-hours.png")
                            .WithAttachment()
                                .WithName("Opening Hours")
                                .WithPath("/assets/desert-bluffs/items/Gas-n-Go-Opening-hours.png")
                            .End()
                        .End()
                    .End()
                    .WithId("gas-n-go")
                    .WithAnnotation("6")
                .End()
                .WithLocation()
                    .WithName("K5N5 Sunset Sounds Radio")
                    .WithDescription(@"Once a modest beacon of local life, the K5N5 Sunset Sounds station now slouches against the desert like a half-buried relic. The squat, single-storey building is built from faded adobe or sun-battered concrete block, its edges soft with time and sand. Its original paint—probably a cheerful rust-red or ochre—has peeled back to reveal the raw material beneath, a kind of skin shed in slow motion.
The signage remains above the building, but a lonely tumbleweed rests beneath it like an offering. Every window is boarded from the inside, giving the building a blind, sealed appearance. What glass remains is fractured, the cracks spidering out like veins frozen mid-thought.
A rusted chain-link fence, long since broken open, encloses the lot. Desert scrub has crept through the gaps, reclaiming the space with brittle patience. To the side of the building, the old radio tower still looms—its latticework rusted through in places, warped by time and storms. Wires dangle from it like dead nerves. One antenna droops, twisted, pointing not at the sky but toward the far mesas like a crooked finger.
Even in daylight, the place casts a long shadow. The heat seems quieter here. The kind of quiet that doesn’t welcome visitors but watches them instead.")
                    .WithImagePath("/assets/desert-bluffs/radio-station/Exterior.png")
                    .WithItemLink()
                        .WithItem()
                            .WithName("Tape - S.W. Overnight Broadcast")
                            .WithImagePath("/assets/desert-bluffs/items/TAPE-overnight-s.w.-broadcast.png")
                            .WithAttachment()
                                .WithName("Audio")
                                .WithPath("/assets/desert-bluffs/items/overnight-s.w.-broadcast.mp3")
                            .End()
                            .WithAttachment()
                                .WithName("Transcript")
                                .WithPath("/assets/desert-bluffs/items/overnight-s.w.-broadcast-transcript.pdf")
                            .End()
                            .WithAttachment()
                                .WithName("Decoded")
                                .WithPath("/assets/desert-bluffs/items/overnight-s.w.-broadcast-decoded.pdf")
                            .End()
                            .WithId("tape-1")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Tape - Shadows in the Heartland")
                            .WithImagePath("/assets/desert-bluffs/items/TAPE-Shadows-in-the-Heartland.jpg")
                            .WithAttachment()
                                .WithName("Audio")
                                .WithPath("/assets/desert-bluffs/items/Shadows-in-the-Heartland.wav")
                            .End()
                            .WithAttachment()
                                .WithName("Transcript")
                                .WithPath("/assets/desert-bluffs/items/Shadows-in-the-Heartland-transcript.pdf")
                            .End()
                            .WithId("tape-2")
                        .End()
                    .End()
                    .WithId("k5n5-sunset-sounds")
                    .WithAnnotation("8")
                .End()
                .WithLocation()
                    .WithName("Lakeside Drive Convenience Store")
                    .WithDescription(@"Settled on the corner of Main Street and Lakeside Drive is the aptly named Lakeside Drive Convenience Store.
The building is modern—single-storey, flat-roofed, with smooth grey brickwork, reddish orange neon signage, and lots of big glass display windows. The sidewalk outside is clear and uncluttered, no ice machines, no vending units.")
                    .WithImagePath("/assets/desert-bluffs/convenience-store/Exterior.png")
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Sarah Sharma")
                            .WithImagePath("/assets/desert-bluffs/Sarah-Sharma.png")
                            .WithFactBasedSummary("Sarah Sharma is in her 30s. She is a qualified pharmacist  who works at the Lakeside Drive Convenience Store. She was born in New York, with family roots in Gujarat, India.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Asian Indian")
                            .WithAgeRange("30s")
                            .WithId("sarah-sharma")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Tommy Nguyen")
                            .WithImagePath("/assets/desert-bluffs/Tommy-Nguyen.png")
                            .WithFactBasedSummary("Tommy Nguyen is in his 30s. He works at the Lakeside Drive Convenience Store as a clerk. He was born and raised in California, with family roots in Vietnam.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Asian Vietnamese")
                            .WithAgeRange("30s")
                            .WithId("tommy-nguyen")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Molly Rivera")
                            .WithImagePath("/assets/desert-bluffs/Molly-Rivera.png")
                            .WithFactBasedSummary("Molly Rivera is in her 20s. She works as a store clerk at the Lakeside Drive Convenience Store. She is married to Carlos Rivera.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Hispanic/Latino")
                            .WithAgeRange("20s")
                            .WithId("molly-rivera")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Evan Michaels")
                            .WithImagePath("/assets/desert-bluffs/Evan-Michaels.png")
                            .WithFactBasedSummary("Evan Michaels is in his 20s. He works as a floor manager at the Lakeside Drive Convenience Store.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Mixed heritage (Black/White)")
                            .WithAgeRange("20s")
                            .WithId("evan-michaels")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Dolores Keene")
                            .WithImagePath("/assets/desert-bluffs/Dolores-Keene.png")
                            .WithFactBasedSummary("Dolores Keene is in her 50s and works as a floor manager at the Lakeside Drive Convenience Store.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("White")
                            .WithAgeRange("50s")
                            .WithId("dolores-keene")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Sam Watkins")
                            .WithImagePath("/assets/desert-bluffs/Sam-Watkins.png")
                            .WithFactBasedSummary("Sam Watkins is in his 40s. He works as a qualified pharmacist at the Lakeside Drive Convenience Store.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("40s")
                            .WithId("sam-watkins")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Lakeside Drive Opening Hours")
                            .WithImagePath("/assets/desert-bluffs/items/Opening-Hours-Lakeside-Drive-Convenience-Store.png")
                            .WithId("lakeside-drive-opening-hours")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Lakeside Drive Incident Log")
                            .WithImagePath("/assets/desert-bluffs/items/Sarah-Sharmas-Incident-Log.png")
                            .WithAttachment()
                                .WithName("The Incident Log")
                                .WithDescription("A PDF version of the incident log")
                                .WithPath("/assets/desert-bluffs/items/Sarah-Sharmas-Incident-Log.pdf")
                            .End()
                            .WithId("lakeside-drive-incident-log")
                        .End()
                    .End()
                    .WithId("convenience-store")
                    .WithAnnotation("9")
                .End()
                .WithLocation()
                    .WithName("McDoonalls")
                    .WithImagePath("/assets/desert-bluffs/mcdoonalls/Exterior.png")
                    .WithItemLink()
                        .WithItem()
                            .WithName("McDoonalls Menu")
                            .WithImagePath("/assets/desert-bluffs/items/McDoonalls-Menu.png")
                            .WithAttachment()
                                .WithName("The Menu")
                                .WithDescription("A PDF version of the menu")
                                .WithPath("/assets/desert-bluffs/items/McDoonalls-Menu.pdf")
                            .End()
                            .WithId("mcdoonalls-menu")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Maya Kaur")
                            .WithImagePath("/assets/desert-bluffs/Maya-Kaur.png")
                            .WithFactBasedSummary("Maya Kaur is in her 30s and serves as the head chef at McDoonalls during the day shift. Originally from an Indian family in Arizona, Maya brings a creative edge to the menu, often enhancing recipes with subtle spice and flavour. Known for her leadership in the kitchen, she is highly respected by her team.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Indian")
                            .WithAgeRange("30s")
                            .WithId("maya-kaur")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Ethan Jackson")
                            .WithImagePath("/assets/desert-bluffs/Ethan-Jackson.png")
                            .WithFactBasedSummary("Ethan Jackson is in his 20s and works as a sous chef on the day shift at McDoonalls. Passionate about learning the culinary arts, he hopes to move up in the industry. Ethan grew up in Desert Bluffs and has a reputation for being detail-oriented and dependable under pressure.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Black")
                            .WithAgeRange("20s")
                            .WithId("ethan-jackson")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Aisha Khan")
                            .WithImagePath("/assets/desert-bluffs/Aisha-Khan.png")
                            .WithFactBasedSummary("Aisha Khan is in her 20s and works as a prep cook on the day shift at McDoonalls. Originally from a Middle Eastern family in California, Aisha is known for her speed and precision in the kitchen. She has an eye for presentation and dreams of one day opening her own café.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Middle Eastern")
                            .WithAgeRange("20s")
                            .WithId("aisha-khan")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacterId("aisha-khan")
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Nina Lee")
                            .WithImagePath("/assets/desert-bluffs/Nina-Lee.png")
                            .WithFactBasedSummary("Nina Lee is in her 30s and works as a cashier and server on the day shift at McDoonalls. As an Asian American raised in the Southwest, she has a warm and approachable manner, which makes her a customer favourite. Nina manages front-of-house operations and has a knack for handling busy shifts smoothly.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Asian American")
                            .WithAgeRange("30s")
                            .WithId("nina-lee")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Oliver Chen")
                            .WithImagePath("/assets/desert-bluffs/Oliver-Chen.png")
                            .WithFactBasedSummary("Oliver Chen is in his 50s and works as a cleaner on the day shift at McDoonalls. A recent immigrant from Taiwan, Oliver is quiet yet meticulous, ensuring the restaurant’s cleanliness is up to standard. He takes pride in his work and values the stability this job provides.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Asian")
                            .WithAgeRange("50s")
                            .WithId("oliver-chen")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Ava Johnson")
                            .WithImagePath("/assets/desert-bluffs/Ava-Johnson.png")
                            .WithFactBasedSummary("Ava Johnson is in her 20s and serves as the floor manager during the day shift at McDoonalls. She is known for her excellent organisational skills and assertive leadership style, handling both staff and customer issues with efficiency. Raised in Desert Bluffs, Ava has long-standing ties to the community.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Black")
                            .WithAgeRange("20s")
                            .WithId("ava-johnson")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jacob Smithy")
                            .WithImagePath("/assets/desert-bluffs/Jacob-Smithy.png")
                            .WithFactBasedSummary("Jacob Smithy is in his 30s and works as the day-shift delivery driver for McDoonalls. A reliable team member with a strong work ethic, he ensures timely and careful deliveries across town. Jake, a Desert Bluffs local, is known for his good humour and customer rapport.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("30s")
                            .WithId("jacob-smithy")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Marcus Wells")
                            .WithImagePath("/assets/desert-bluffs/Marcus-Wells.png")
                            .WithFactBasedSummary("Marcus Wells is in his 30s and leads the evening shift as head chef at McDoonalls. A culinary school graduate from a nearby city, Marcus returned to Desert Bluffs with a desire to give back to his community. His inventive takes on classic dishes make him a staff favourite.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Black")
                            .WithAgeRange("30s")
                            .WithId("marcus-wells")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Ahmed El-Sayed")
                            .WithImagePath("/assets/desert-bluffs/Ahmed-El-Sayed.png")
                            .WithFactBasedSummary("Ahmed El-Sayed is in his 20s, serving as a prep cook on the evening shift at McDoonalls. Born to an Egyptian family in Texas, Ahmed is dedicated and focused on developing his skills. He dreams of working in a high-end restaurant and treats each shift as a step toward that goal.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Middle-Eastern (Egyptian)")
                            .WithAgeRange("20s")
                            .WithId("ahmed-el-sayed")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Jimmy Parker")
                            .WithImagePath("/assets/desert-bluffs/Jimmy-Parker.png")
                            .WithFactBasedSummary("Jimmy Parker is in his 50s and works as a cleaner on the evening shift at McDoonalls. Known for his reliability, Jimmy takes pride in keeping the restaurant spotless. Originally from the Midwest, he settled in Desert Bluffs after travelling extensively.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("50s")
                            .WithId("jimmy-parker")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Naomi Chang")
                            .WithImagePath("/assets/desert-bluffs/Naomi-Chang.png")
                            .WithFactBasedSummary("Naomi Chang is in her 40s and serves as the floor manager during the evening shift at McDoonalls, handling both managerial and cashier duties. A lifelong resident of Desert Bluffs, Naomi is known for her supportive leadership style and efficiency, ensuring smooth operations and attentive service for evening customers.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Asian American")
                            .WithAgeRange("40s")
                            .WithId("naomi-chang")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Mila Redbird")
                            .WithImagePath("/assets/desert-bluffs/Mila-Redbird.png")
                            .WithFactBasedSummary("Mila Redbird is in her 30s and heads the night shift as lead chef at McDoonalls. Having worked in fast-paced city diners, she values the quieter atmosphere in Desert Bluffs. Olivia is known for her speed and precision, keeping the kitchen moving during the late hours.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Tashké")
                            .WithAgeRange("30s")
                            .WithId("mila-redbird")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Ravi Sharma")
                            .WithImagePath("/assets/desert-bluffs/Ravi-Sharma.png")
                            .WithFactBasedSummary("Ravi Sharma is in his 20s and works as a prep cook on the night shift at McDoonalls. Born in a large Indian family in Nevada, Ravi is eager to prove himself in the kitchen. He is quick to pick up new skills and is known for his strong work ethic.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Indian")
                            .WithAgeRange("20s")
                            .WithId("ravi-sharma")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Chloe Hayes")
                            .WithImagePath("/assets/desert-bluffs/Chloe-Hayes.png")
                            .WithFactBasedSummary("Chloe Hayes is in her 20s and serves as a cashier and server during the night shift. Friendly and attentive, she ensures customers feel welcome even during the late hours. Chloe, a lifelong resident of Desert Bluffs, is known for her sunny disposition.")
                            .WithPronouns("She/Her")
                            .WithDiversityFlag("Black")
                            .WithAgeRange("20s")
                            .WithId("chloe-hayes")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Sam Rivera")
                            .WithImagePath("/assets/desert-bluffs/Sam-Rivera.png")
                            .WithFactBasedSummary("Sam Rivera is in his 30s and works as a runner and cleaner on the night shift at McDoonalls, ensuring supplies and orders are timely. Originally from Arizona, Sam brings energy and efficiency to his role, keeping operations smooth even on busy nights.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("Hispanic/Latino")
                            .WithAgeRange("30s")
                            .WithId("sam-rivera")
                        .End()
                    .End()
                    .WithId("mcdoonalls")
                    .WithAnnotation("11")
                .End()
                .WithLocation()
                    .WithName("Nuts & Screws")
                    .WithDescription(@"* Nuts & Screws is a useful location for the players to visit.
* They can gain both useful items and information here if they invest the time to roleplay.
* The owners, Harry and Gene, have lived in Desert Bluffs all their lives.
* They can provide clear narrative information about the 1980s, Father Jack, the shadow creatures, and how the town has changed for the better over the decades.
* They can also provide an undercurrent of concern that shadow creatures are returning.
* The store contains almost anything mundane and reasonable that the players want to buy.")
                    .WithImagePath("/assets/desert-bluffs/nuts-n-screws/Exterior.png")
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Harold 'Harry' Harrison")
                            .WithImagePath("/assets/desert-bluffs/Harry-and-Gene-Harrison.png")
                            .WithFactBasedSummary("Harry Harrison is in his 50s and is a co-owner of the hardware store Nuts & Screws. He is married to Gene Harrison.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithDiversityFlag("Gay")
                            .WithAgeRange("70s")
                            .WithId("harry-harrison")
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Eugene 'Gene' Harrison")
                            .WithImagePath("/assets/desert-bluffs/Harry-and-Gene-Harrison.png")
                            .WithFactBasedSummary("Gene Harrison is in his 50s and is a co-owner of the hardware store Nuts & Screws. He is married to Harry Harrison. His surname before marriage was Jones.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithDiversityFlag("Gay")
                            .WithAgeRange("70s")
                            .WithId("gene-harrison")
                        .End()
                    .End()
                    .WithId("nuts-n-screws")
                    .WithAnnotation("12")
                .End()
                .WithLocation()
                    .WithName("Sheriff's Office")
                    .WithDescription(@"* This building adds atmosphere to the mystery, but it is not essential to explore.
* There are non-essential clues available at the Sheriff’s Office.
* The players might encounter minions in the darkest areas of the building in the daytime.
* The players will encounter minions in the darkest areas of the building at night.
* It is a low single storey building. 
* The parking lot is empty, with a flagpole outside the building. 
* Someone has made sure the stars and stripes still fly, despite the building being disused.
* The windows are boarded up from the inside, some of the glass is broken. However, the panes are small, and the boarding is robust—there is no easy window access without effort
* There is no easy roof access.
* The front door is security glass with chains looped between the handles, secured by an old and now somewhat rusted padlock. The front lobby door padlock is breakable with force or tools. This entry gives access to the lobby area.
* There is a fire exit at the back, this has been locked shut from the inside. This entry gives access to the hallway.
* The roof has some skylights. The skylights can give entry to the lobby area, the back office, the staff kitchen, or the restrooms.
* Inside, every area is dusty, grimy with age, and there are cobwebs. 
* Some areas smell of damp, decay, and rust.
* The building has no power or running water.
* The building is old fashioned and does not have accessible features or unisex facilities.")
                    .WithImagePath("/assets/desert-bluffs/sheriffs-office/Exterior.png")
                    .WithItemLink("map")
                    .WithItemLink()
                        .WithItem()
                            .WithName("Poster: Buckle Up")
                            .WithImagePath("/assets/desert-bluffs/items/Buckle-Up.png")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Poster: Bake Sale")
                            .WithImagePath("/assets/desert-bluffs/items/Bake-Sale.png")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Sherriff's Office Note")
                            .WithImagePath("/assets/desert-bluffs/items/Sheriffs-Office-note-as-found.png")
                            .WithAttachment()
                                .WithName("As Found")
                                .WithPath("/assets/desert-bluffs/items/Sheriffs-Office-note-as-found.png")
                            .End()
                            .WithAttachment()
                                .WithName("Cleared up")
                                .WithPath("/assets/desert-bluffs/items/Sheriffs-Office-note-clearer.png")
                            .End()
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("Sherriff's Incident Report")
                            .WithImagePath("/assets/desert-bluffs/items/Incident-Report.png")
                            .WithAttachment()
                                .WithName("The Report")
                                .WithPath("/assets/desert-bluffs/items/Incident-Report.png")
                            .End()
                        .End()
                    .End()
                    .WithCharacterLink()
                        .WithCharacter()
                            .WithName("Alan Mallory")
                            .WithFactBasedSummary("Alan Mallory was a deputy in the Sheriff's Office in 1984. He was a cousin to Edna Mallory, aged in his 30s in 1984.")
                            .WithPronouns("He/Him")
                            .WithDiversityFlag("White")
                            .WithAgeRange("30s")
                            .WithId("alan-mallory")
                            .WithAnnotation("Deceased?")
                        .End()
                    .End()
                    .WithId("sheriffs-office")
                    .WithAnnotation("15")
                .End()
                .WithLocation()
                    .WithName("Vista School & Spiderweb Field")
                    .WithDescription(@"Structure: Primarily a single-storey structure with a small, raised admin tower. Flat-roofed, built in 1957 with tan brick and white-painted steel window frames.
Windows: Many are fogged with dust or cracked; a few have been broken.

Entrances:
* Front double doors (glass and aluminium) are padlocked and secured with chain
* Side staff entrance rusted shut
* Rear service door (metal, dented) shows signs of previous access

Grounds:
* Former lawn is overgrown with waist-high weeds and scattered debris
* Playground removed; anchor points and rusted bolts remain
* Concrete walkway buckled in places by tree roots

Above the main entrance, a faded mural reads: ""Vista School – Home of the Sun Spiders"" with a stylised golden arachnid over a sunburst.

One cracked banner frame still displays: ""Go Spiders! 2013 County Semi-Finalists"".

Spiderweb Field:
* Located just beyond the back fence, access via a worn gravel path
* Chain-link fencing surrounds a dirt diamond, now overtaken by dry grass
* Bleachers are sun-bleached and slightly warped, paint flakes from metal frames
* The scoreboard still stands — rusted, non-functional, labelled “Spiderweb Field” in curling script

Condition:
* Mild vandalism (graffiti, minor window damage), but mostly abandonment and environmental decay
* Occasional bird nests and vermin droppings around vents and eaves")
                    .WithImagePath("/assets/desert-bluffs/school-and-field/Exterior.png")
                    .WithItemLink()
                        .WithItem()
                            .WithName("School Graffiti #1")
                            .WithImagePath("/assets/desert-bluffs/school-and-field/graffiti-1.jpg")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("School Graffiti #2")
                            .WithImagePath("/assets/desert-bluffs/school-and-field/graffiti-2.jpg")
                        .End()
                    .End()
                    .WithItemLink()
                        .WithItem()
                            .WithName("School Graffiti #3")
                            .WithImagePath("/assets/desert-bluffs/school-and-field/graffiti-3.jpg")
                        .End()
                    .End()
                    .WithId("school-and-field")
                    .WithAnnotation("18")
                .End()
                .WithLocation()
                    .WithName("House Behind The Diner")
                    .WithDescription("A modest single-storey adobe-style home sits behind the diner, shaded by a mesquite tree and surrounded by a tidy garden of succulents, desert herbs, and wind chimes. The house is painted a soft clay-red with sun-bleached teal trim around the doors and windows. The front porch has two well-worn rocking chairs and a small metal table for morning coffee.")
                    .WithImagePath("/assets/desert-bluffs/house-behind-diner/Exterior.png")
                    .WithCharacterLink()
                        .WithCharacterId("betty-white")
                    .End()
                    .WithCharacterLink()
                        .WithCharacterId("lizzy-black")
                    .End()
                    .WithId("house-behind-diner")
                    .WithAnnotation("19")
                .End()
                .WithLocation()
                    .WithName("Suncrest Communications")
                    .WithDescription(@"The building is a mid-century modern structure, long past its prime. The exterior is mostly made of ochre concrete, with large windows that are now cracked, dirt streaked and boarded up from the inside. The glass panes have been shattered in places, giving the building a fractured look as though it's barely holding onto its past. 
There's a rusted metal sign above the door that used to proudly display the company’s name, but now it’s barely legible, peeling away with age. The parking lot is overgrown with weeds, and a few stray papers, plastic wrappers, and forgotten objects are scattered around the entrance. The doorframe has been boarded up with weathered planks, but the remnants of the original glass door still hang loosely from their hinges. The once well-maintained grounds have been overtaken by wild, unkempt grass and the occasional stray cat.
To the left of the building is a long, empty warehouse, its exterior just as neglected, with faded graffiti scrawled on the walls. The once vibrant colours of the street art have long since dulled, giving it a forgotten, desolate air. Old equipment and parts lie scattered around the back, overrun with rust and corrosion. The smell of rust, mildew, and dust lingers in the air.")
                    .WithImagePath("/assets/desert-bluffs/suncrest-communications/Exterior.png")
                    .WithId("suncrest-communications")
                    .WithAnnotation("20")
                .End()
                .WithId("desert-bluffs")
            .End();
    }
}