using System.Reflection;

namespace Kadense.RPG.Models;

public partial class GamesFactory : GameFactoryBase
{
    [Game("Honey Heist")]
    public GamesFactory AddHoneyHeist()
    {
        var attr = MethodInfo.GetCurrentMethod()!.GetCustomAttribute<GameAttribute>()!;
        return this
            .WithGame(attr.Name, attr.Description ?? "TBD Add Description")
                .WithWorldSection()
                    .WithLlmPrompt(@"""Generate a brief introduction to a heist game, where the players are bears trying to steal honey. The bears are planning a heist at a {feel} {location} where they will also find {prize}. The bears have a plan, but little do they know that {twist}. Do not reveal this twist but do set it up, along with a number of other random elements to throw off the players. Do not include a header or title.""")
                    .WithSelection("Feel")
                        .WithVariableName("feel")
                        .WithNewChoice("Creepy")
                        .WithNewChoice("Busy")
                        .WithNewChoice("Run-down")
                        .WithNewChoice("Beautiful")
                        .WithNewChoice("Dangerous")
                        .WithNewChoice("Lavish")
                    .End()
                    .WithSelection("Location")
                        .WithVariableName("location")
                        .WithNewChoice("Lakeside Camp")
                        .WithNewChoice("Fishing Village")
                        .WithNewChoice("Metropolitan City")
                        .WithNewChoice("Convention Center")
                        .WithNewChoice("Truck Convoy")
                        .WithNewChoice("Wilderness Retreat")
                    .End()
                    .WithSelection("The prize (aside from Honey)")
                        .WithVariableName("prize")
                        .WithNewChoice("Ultra dense mega honey from especially posh bees")
                        .WithNewChoice("A briefcase of pure manuka extract worth of $5 million")
                        .WithNewChoice("The queen of all bees, once exiled, now returned")
                        .WithNewChoice("Abraham Lincoln's beehive, thought to be haunted by his Ghost")
                        .WithNewChoice("Miss universe 2017, an especially attractive bee")
                    .End()
                    .WithSelection("But little do the bears know")
                        .WithVariableName("twist")
                        .WithNewChoice("This place is rigged to blow")
                        .WithNewChoice("The cops are already en route")
                        .WithNewChoice("There's a rival team of bears")
                        .WithNewChoice("They've been setup")
                        .WithNewChoice("The prize is a fake")
                        .WithNewChoice("The bees are angry")
                    .End()
                .End()
                .WithCharacterSection()
                    .WithSelection("Bear Type")
                        .WithChoice("Grizzly Bear")
                            .WithAttribute("Skill", "Terrify")
                        .End()
                        .WithChoice("Polar Bear")
                            .WithAttribute("Skill", "Swim")
                        .End()
                        .WithChoice("Panda Bear")
                            .WithAttribute("Skill", "Eat anything that looks like bamboo")
                        .End()
                        .WithChoice("Black Bear")
                            .WithAttribute("Skill", "Climb")
                        .End()
                        .WithChoice("Sun Bear")
                            .WithAttribute("Skill", "Sense honey")
                        .End()
                        .WithChoice("Honey Badger")
                            .WithAttribute("Skill", "Carnage")
                        .End()
                    .End()
                    .WithSelection("Descriptor")
                        .WithNewChoice("Rookie")
                        .WithNewChoice("Washed-up")
                        .WithNewChoice("Retired")
                        .WithNewChoice("Unhinged")
                        .WithNewChoice("Slick")
                        .WithNewChoice("Incompetent")
                    .End()
                    .WithSelection("Role")
                        .WithNewChoice("Muscle")
                        .WithNewChoice("Brains")
                        .WithNewChoice("Driver")
                        .WithNewChoice("Hacker")
                        .WithNewChoice("Thief")
                        .WithNewChoice("Face")
                    .End()
                    .WithSelection("Hat", "(This is optional, but highly recommended)")
                        .WithNewChoice("Trilby")
                        .WithNewChoice("Top")
                        .WithNewChoice("Bowler")
                        .WithNewChoice("Flat cap")
                        .WithNewChoice("Cowboy")
                        .WithNewChoice("Fez")
                        .WithNewChoice("Crown")
                    .End()
                .End()
            .End();
    }
}

