using System.Reflection;

namespace Kadense.RPG.Models;

public partial class GamesFactory : GameFactoryBase
{
    [Game(
        "The Witch is Dead",
        Description = @"""
            Once upon a time, there was a kind and wise and beautiful witch who lived in the forest with her familiars. 
            
            Her life was peaceful and happy, until a fucking Witch Hunter broke into her cottage, dragged her out and fucking murdered her. 

            Now she's dead, but if you get revenge for her, kill him and bring his eyes to her corpse within one week, she will come back to life (or so you've heard). Even if it doesn't work, at least he's dead.
        """
    )]
    public GamesFactory AddTheWitchIsDead()
    {
        var attr = MethodInfo.GetCurrentMethod()!.GetCustomAttribute<GameAttribute>()!;
        return this
            .WithGame(attr.Name, attr.Description ?? "TBD Add Description")
                .WithWorldSection()
                    .WithLlmPrompt(@"""Generate a brief introduction to a fantasy game, where the players are animals trying to avenge the death of a witch. The players suspect that the witch was killed by a {witchHunter} Witch Hunter in a {village} village. The players must find the witch hunter and kill them, but little do they know that {twist}. Do not reveal this twist but do set it up, along with a number of other random elements to throw off the players. Do not include a header or title.""")
                    .WithSelection("The village is")
                        .WithVariableName("village")
                        .WithNewChoice("Under the thumb of the Baron")
                        .WithNewChoice("Filled with cheery Gnomes")
                        .WithNewChoice("Controlled by a creepy cult")
                        .WithNewChoice("Devolutly religious")
                        .WithNewChoice("Incredibly superstitious")
                        .WithNewChoice("At war with forest tribes")
                        .WithNewChoice("Built around a wizard's college")
                        .WithNewChoice("Full of hardy mining folk")
                        .WithNewChoice("Shady and dangerous")
                        .WithNewChoice("Oppressively perfect")
                    .End()
                    .WithSelection("The Witch Hunter is")
                        .WithVariableName("witchHunter")
                        .WithNewChoice("Armoured and tough")
                        .WithNewChoice("Wizened and wise")
                        .WithNewChoice("Drunk and violent")
                        .WithNewChoice("Pios and aggressive")
                        .WithNewChoice("Guarded and cowardly")
                        .WithNewChoice("Magical and jealous")
                        .WithNewChoice("Clever and cruel")
                        .WithNewChoice("Duplicitous and hidden")
                        .WithNewChoice("Jolly and well-meaning")
                        .WithNewChoice("Headstrong and wild")
                    .End()
                    .WithSelection("The twist is")
                        .WithVariableName("twist")
                        .WithNewChoice("The village are in on it")
                        .WithNewChoice("A rival witch set her up")
                        .WithNewChoice("The witch-hunter didn't do it")
                        .WithNewChoice("The witch-hunter is waiting for you")
                        .WithNewChoice("The village folk are having a festival")
                        .WithNewChoice("The witch-hunter died, and is being buried")
                        .WithNewChoice("There are two (rival) witch-hunters in town")
                        .WithNewChoice("The village is abandoned")
                        .WithNewChoice("The witch-hunter has dragged a suspected up for interrogation")
                        .WithNewChoice("The village hates him")
                    .End()
                .End()
                .WithCharacterSection()
                    .WithSelection("Species")
                        .WithChoice("Fox")
                            .WithAttribute("Clever", "2")
                            .WithAttribute("Fierce", "2")
                            .WithAttribute("Sly", "1")
                            .WithAttribute("Quick", "1")
                        .End()
                        .WithChoice("Cat")
                            .WithAttribute("Clever", "0")
                            .WithAttribute("Fierce", "1")
                            .WithAttribute("Sly", "3")
                            .WithAttribute("Quick", "2")
                        .End()
                        .WithChoice("Toad")
                            .WithAttribute("Clever", "1")
                            .WithAttribute("Fierce", "0")
                            .WithAttribute("Sly", "2")
                            .WithAttribute("Quick", "1")
                        .End()
                        .WithChoice("Spider")
                            .WithAttribute("Clever", "2")
                            .WithAttribute("Fierce", "0")
                            .WithAttribute("Sly", "3")
                            .WithAttribute("Quick", "1")
                        .End()
                        .WithChoice("Owl")
                            .WithAttribute("Clever", "3")
                            .WithAttribute("Fierce", "1")
                            .WithAttribute("Sly", "1")
                            .WithAttribute("Quick", "2")
                        .End()
                        .WithChoice("Hare")
                            .WithAttribute("Clever", "0")
                            .WithAttribute("Fierce", "0")
                            .WithAttribute("Sly", "2")
                            .WithAttribute("Quick", "3")
                        .End()
                        .WithChoice("Magpie")
                            .WithAttribute("Clever", "2")
                            .WithAttribute("Fierce", "1")
                            .WithAttribute("Sly", "1")
                            .WithAttribute("Quick", "2")
                        .End()
                        .WithChoice("Crow")
                            .WithAttribute("Clever", "2")
                            .WithAttribute("Fierce", "1")
                            .WithAttribute("Sly", "2")
                            .WithAttribute("Quick", "1")
                        .End()
                        .WithChoice("Dog")
                            .WithAttribute("Clever", "1")
                            .WithAttribute("Fierce", "3")
                            .WithAttribute("Sly", "0")
                            .WithAttribute("Quick", "1")
                        .End()
                        .WithChoice("Rat")
                            .WithAttribute("Clever", "1")
                            .WithAttribute("Fierce", "0")
                            .WithAttribute("Sly", "2")
                            .WithAttribute("Quick", "2")
                        .End()
                    .End()
                    .WithSelection("Spell")
                        .WithNewChoice("Unseen Hand")
                        .WithNewChoice("Conjure Light")
                        .WithNewChoice("Speak Human")
                        .WithNewChoice("Lock / Unlock, Open / Close")
                        .WithNewChoice("Conjure Dinner")
                        .WithNewChoice("Make Flame")
                        .WithNewChoice("Tidy, Clean, and Mend")
                        .WithNewChoice("Plant Growth")
                        .WithNewChoice("Distract / Confuse")
                        .WithNewChoice("Make book read itself out loud")
                    .End()
                .End()
            .End();
    }
}

