using System.Reflection;

namespace Kadense.RPG.Models;

public partial class GamesFactory : GameFactoryBase
{
    [Game("Trashkin")]
    public GamesFactory Trashkin()
    {
        var attr = MethodInfo.GetCurrentMethod()!.GetCustomAttribute<GameAttribute>()!;
        return this
            .WithGame(attr.Name, attr.Description ?? "TBD Add Description")
                .WithWorldSection()
                    .WithLlmPrompt(@"""
                    Generate a brief descriptive introduction to a game. The setting is a trash heap in a {state} {location}.
                    The heap contains a big treasure which is a {treasure} and is guarded by {guardedBy}. 
                    Their mission is to steal the {treasure}.
                    Add some random elements for flair.
                    Do not include a title or header.
                    """)
                    .WithSelection("State")
                        .WithVariableName("state")
                        .WithNewChoice("Decrepit")
                        .WithNewChoice("Overpopulated")
                        .WithNewChoice("Kinda magical")
                        .WithNewChoice("Probably evil")
                        .WithNewChoice("Ambulatory")
                        .WithNewChoice("Haunted")
                    .End()
                    .WithSelection("Location")
                        .WithVariableName("location")
                        .WithNewChoice("Frontier town")
                        .WithNewChoice("Dungeon")
                        .WithNewChoice("Mansion")
                        .WithNewChoice("Capital city")
                        .WithNewChoice("Elven Forest")
                        .WithNewChoice("Dwarven hold")
                    .End()
                    .WithSelection("Big Treasure")
                        .WithVariableName("treasure")
                        .WithNewChoice("Goblin Princess's Stash")
                        .WithNewChoice("Apparatus of the Crab")
                        .WithNewChoice("Wagon full of garbage")
                        .WithNewChoice("Nearly-full swear jar")
                        .WithNewChoice("Job lot of soiled wigs")
                        .WithNewChoice("Christmas tree")
                    .End()
                    .WithSelection("Guarded by")
                        .WithVariableName("guardedBy")
                        .WithNewChoice("Dangerous animals")
                        .WithNewChoice("Normal people")
                        .WithNewChoice("Rag-tag kobold sappers")
                        .WithNewChoice("Rival trashkin gang")
                        .WithNewChoice("Gullboy gangsters")
                        .WithNewChoice("Wizard and her familiars")
                    .End()
                .End()
                .WithCharacterSection()
                    .WithRandomAttribute("Audacious")
                    .WithRandomAttribute("Cunning")
                    .WithRandomAttribute("Big")
                    .WithRandomAttribute("Quick")
                    .WithSelection("Race")
                        .WithChoice("Raccoonkin")
                            .WithAttribute("Damage", "d6")
                            .WithAttribute("Audacious", "+1")
                            .WithAttribute("Cunning", "+1")
                            .WithSelection("Ability")
                                .WithNewChoice("Filthball", "Hurl a stinking orb of trash around")
                                .WithNewChoice("Trashstep", "Teleport between a pile of trash and another that you can see")
                                .WithNewChoice("Meld with trash", "Really get in there")
                                .WithNewChoice("Trash Glider", "Fashion a sort of paraglider out of stuff")
                                .WithNewChoice("Find Grot", "Divine the location of the nearest discarded erotica")
                                .WithNewChoice("Vorpal Tin Lid", "Gods, this thing is sharp!")
                            .End()
                        .End()
                        .WithChoice("Pigeonkin")
                            .WithAttribute("Damage", "d4")
                            .WithAttribute("Audacious", "+1")
                            .WithAttribute("Big", "-1")
                            .WithAttribute("You can", "Fly (a bit)")
                            .WithAttribute("You can also", "Smoke cigarettes")
                        .End()
                        .WithChoice("Ratboy")
                            .WithAttribute("Damage", "d4")
                            .WithAttribute("Quick", "+2")
                            .WithAttribute("You can", "Add quick damage to unaware targets")
                        .End()
                        .WithChoice("Foxfolk")
                            .WithAttribute("Damage", "d4")
                            .WithAttribute("Cunning", "+2")
                            .WithAttribute("You can", "Add quick damage to unaware targets")
                            .WithSelection("Ability")
                                .SetNumberToChoose(2)
                                .WithNewChoice("Filthball", "Hurl a stinking orb of trash around")
                                .WithNewChoice("Trashstep", "Teleport between a pile of trash and another that you can see")
                                .WithNewChoice("Meld with trash", "Really get in there")
                                .WithNewChoice("Trash Glider", "Fashion a sort of paraglider out of stuff")
                                .WithNewChoice("Find Grot", "Divine the location of the nearest discarded erotica")
                                .WithNewChoice("Vorpal Tin Lid", "Gods, this thing is sharp!")
                            .End()
                        .End()
                        .WithChoice("Half-Possum")
                            .WithAttribute("Damage", "d4")
                            .WithAttribute("Audacity", "+2")
                            .WithSelection("Ability")
                                .SetNumberToChoose(2)
                                .WithNewChoice("Animate Skellington", "Mainly small stuff like fish bones, etc")
                                .WithNewChoice("Apply used plaster", "Heal someone for d4 coppers")
                                .WithNewChoice("Play Undead", "Appear as a corpse, walking, or otherwise")
                                .WithNewChoice("Bone Armor", "Animate, then climb into a chicken carcass")
                                .WithNewChoice("Summon Trash Elemental", "It's just awful")
                                .WithNewChoice("Spit Hex", "Briefly blind or deafen a nearby foe")
                            .End()
                        .End()
                        .WithChoice("Goat-Girl")
                            .WithAttribute("Damage", "d6")
                            .WithAttribute("Big", "+1")
                            .WithAttribute("Audacious", "+1")
                            .WithAttribute("Charging in", "+1")
                            .WithAttribute("Ability", "Eat Tin Cans (and other stuff), it's your birthday!")
                            .WithSelection("Another Ability")
                                .WithNewChoice("Animate Skellington", "Mainly small stuff like fish bones, etc")
                                .WithNewChoice("Apply used plaster", "Heal someone for d4 coppers")
                                .WithNewChoice("Play Undead", "Appear as a corpse, walking, or otherwise")
                                .WithNewChoice("Bone Armor", "Animate, then climb into a chicken carcass")
                                .WithNewChoice("Summon Trash Elemental", "It's just awful")
                                .WithNewChoice("Spit Hex", "Briefly blind or deafen a nearby foe")
                            .End()
                        .End()
                    .End()
                    .WithSelection("Armour")
                        .WithChoice("A dress, socks, a stolen hood, etc")
                            .WithAttribute("Copper", "+0")
                        .End()
                        .WithChoice("A dress, socks, a stolen hood, etc")
                            .WithAttribute("Copper", "+0")
                        .End()
                        .WithChoice("A dress, socks, a stolen hood, etc")
                            .WithAttribute("Copper", "+0")
                        .End()
                        .WithChoice("Boxes, bits of barrel, a very chunky sweater")
                            .WithAttribute("Copper", "+3")
                            .WithAttribute("Quick", "-1")
                        .End()
                        .WithChoice("Boxes, bits of barrel, a very chunky sweater")
                            .WithAttribute("Copper", "+3")
                            .WithAttribute("Quick", "-1")
                        .End()
                        .WithChoice("Pans, bins, a stove, etc")
                            .WithAttribute("Copper", "+5")
                            .WithAttribute("Quick", "-2")
                        .End()
                    .End()
                    .WithSelection("Melee")
                        .WithChoice("Bare hands")
                            .WithAttribute("Damage", "+0")
                        .End()
                        .WithChoice("Chair leg, bottle, etc")
                            .WithAttribute("Damage", "+1")
                            .WithAttribute("Quick", "-1")
                        .End()
                        .WithChoice("Mallet, Stolen Sword")
                            .WithAttribute("Damage", "+3")
                            .WithAttribute("Quick", "-2")
                        .End()
                    .End()
                    .WithSelection("Ranged")
                        .WithNewChoice("None")
                        .WithChoice("Sackful of stones, catapult, sling")
                            .WithAttribute("Damage", "+0")
                        .End()
                        .WithChoice("Sackful of stones, catapult, sling")
                            .WithAttribute("Damage", "+0")
                        .End()
                        .WithChoice("Sackful of stones, catapult, sling")
                            .WithAttribute("Damage", "+0")
                        .End()
                        .WithChoice("Bricks, shortbow, etc")
                            .WithAttribute("Damage", "+2")
                            .WithAttribute("Quick", "-1")
                        .End()
                    .End()
                    .WithSelection("\"Magic\" Item")
                        .WithNewChoice("Gold Coin", "Used to buy goods and services")
                        .WithNewChoice("Dynamite", "Who'd throw that away anyway?")
                        .WithNewChoice("Springs", "Big bouncy ones")
                        .WithNewChoice("False Teeth", "Not the wind up kind, the \"been in someone's mouth\" kind")
                        .WithNewChoice("Hat \"of disguise\"", "Not even slightly magical")
                        .WithNewChoice("Zippo's box of conflagration", "A lighter")
                        .WithNewChoice("Potion of ...", "... something?")
                        .WithNewChoice("A wand with one charge left", "Hope it's a good spell")
                        .WithNewChoice("Gin", "There's some left in the bottle")
                        .WithNewChoice("Threadbare Trench-coat", "Get Stacking")
                    .End()
                .End()
            .End();
    }
}

